# fly.toml app configuration file generated for usdc-dance-relayer on 2026-02-20T00:39:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'usdc-dance-relayer'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  STORY_AENEID_RPC = 'https://aeneid.storyrpc.io'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
